### ISSUE TITLE
logp_old isn't summed

### ISSUE THREAD

**Issue by danielhomola** [sid-sundrani/ppo_lightning#4]
I think [this line](https://github.com/sid-sundrani/ppo_lightning/blob/master/ppo_model.py#L233) should be
```{python}
ratio = torch.exp(logp - logp_old.sum(-1))
```
What do you reckon? 

Also, as far as I can tell, the `forward` function isn't used anywhere.. I suppose it's just there so one can generate actions with a trained agent?

**Comment by sidhantls** [comment]
Wouldn't that lead to the size of `logp` being different from `logp_old.sum(-1)`? They should be of the same shape 

Yes `forward` of the lightning module isn't used anywhere. You can use it to generate actions with but you can also just call model.agent for that matter

**Comment by danielhomola** [comment]
I modified the distribution from Normal to Dirichlet, that's why I ran into this. You're right, it should stay as it is! 

Thanks!
